"""create devices table

Revision ID: 05fc3a8367d8
Revises: a3ee1e06121c
Create Date: 2026-01-13 17:43:34.225750

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "05fc3a8367d8"
down_revision: Union[str, Sequence[str], None] = "a3ee1e06121c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "devices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("DRONE", "EXO", "SENSOR", name="device_kind"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "ONLINE", "OFFLINE", "MAINTENANCE", "DEGRADED", name="device_status"
            ),
            server_default="OFFLINE",
            nullable=False,
        ),
        sa.Column("battery", sa.Integer(), server_default="100", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("devices")
    # ### end Alembic commands ###
