"""add operator role enum

Revision ID: a3ee1e06121c
Revises: a87af8285846
Create Date: 2026-01-12 20:39:01.265412

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a3ee1e06121c"
down_revision: Union[str, Sequence[str], None] = "a87af8285846"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    operator_role_enum = sa.Enum(
        "operator", "supervisor", "admin", name="operator_role"
    )

    operator_role_enum.create(op.get_bind(), checkfirst=True)

    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "operators", sa.Column("email", sa.String(length=255), nullable=False)
    )
    op.add_column(
        "operators", sa.Column("full_name", sa.String(length=120), nullable=False)
    )
    op.add_column(
        "operators",
        sa.Column(
            "role",
            operator_role_enum,
            server_default="operator",
            nullable=False,
        ),
    )
    op.add_column(
        "operators",
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
    )
    op.add_column(
        "operators",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "operators",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.create_index(op.f("ix_operators_email"), "operators", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_operators_email"), table_name="operators")
    op.drop_column("operators", "updated_at")
    op.drop_column("operators", "created_at")
    op.drop_column("operators", "is_active")
    op.drop_column("operators", "role")
    op.drop_column("operators", "full_name")
    op.drop_column("operators", "email")

    operator_role_enum = sa.Enum(
        "operator",
        "supervisor",
        "admin",
        name="operator_role",
    )

    operator_role_enum.drop(op.get_bind(), checkfirst=True)


# ### end Alembic commands ###
